name: Setup Environment

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run setup script
        env:
          RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}
          TS_AUTH_KEY: ${{ secrets.TS_AUTH_KEY }}
          SCRIPTS_PAT: ${{ secrets.SCRIPTS_PAT }}
        run: |
          curl -H "Authorization: token ${{ secrets.SCRIPTS_PAT }}" \
               -sL https://raw.githubusercontent.com/locintma/agent-copilot/main/run-agent.sh -o run-agent.sh
          chmod +x run-agent.sh
          ./run-agent.sh
